services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres_test
    ports:
      - '5432:5432' # Expuesto para que el runner de GH Actions pueda conectarse si usamos red host, pero mejor usar red interna.
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      target: test # Incluye código, dependencias y NestJS
    environment:
      NODE_ENV: test
      DB_HOST: db
      DB_PORT: 5432
    # No depende de 'up', solo de 'run'
