services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: call-order-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      target: build # Usamos la etapa BUILD para tener TypeScript y hot-reload
    command: npm run start:dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app # Montamos código fuente para hot-reload
      - /app/node_modules # Previene conflictos
    depends_on:
      - db

volumes:
  postgres_data:
